### ISSUE TITLE
Update IIIF endpoints to support rights and licensing statements 

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#109]
Update rose and aor content so that appropriate rights statements are made.
For example AoR distributes images with a certain CC license.

**Comment by jabrah** [comment]
IIIF Image API v2.0 does not specify properties for license/attribution/logo. These are being added for v2.1

**Comment by jabrah** [comment]
Presentation API (should) already have attribution, must wait to update to IIIF Image v2.1 to get attribution on images (#146)

**Comment by jabrah** [comment]
Our IIIF Image endpoint currently has support for rights and attribution, however, there is no way to extract such information, as there is no dependency on the archive.
