### ISSUE TITLE
Document archive directory structure, file formats, and import procedure on wiki

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#11]

**Comment by markpatton** [comment]
Also document tool.

**Comment by jabrah** [comment]
Must also document Shared Canvas transformations, implementations, etc

**Comment by jabrah** [comment]
@markpatton please review current documentation on the wiki when you have time. These pages are currently incomplete, but should provide a good starting point.

 * [Rose Archive](https://github.com/jhu-digital-manuscripts/rosa2/wiki/Rosa-Archive)
 * [Importing Data](https://github.com/jhu-digital-manuscripts/rosa2/wiki/Importing-Data-Into-the-Archive)
 * [IIIF Transforms](https://github.com/jhu-digital-manuscripts/rosa2/wiki/Archive-to-IIIF-Presentation-model-transforms)
