### ISSUE TITLE
Update GWT to version 2.8

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#112]
Version 2.8 adds java 8 support. Ensure that our modules using GWT are complied with java 8 support enabled.

**Comment by markpatton** [comment]
Version 2.8 is in beta now, wait until the stable release to update.

**Comment by markpatton** [comment]
Also update the gwt-maven-plugin at the same time.

**Comment by jabrah** [comment]
[GWT 2.8.0-rc2](https://groups.google.com/forum/#!topic/google-web-toolkit/udNQeQ6cK8A) currently out. No date on next release candidate or full release.

**Comment by markpatton** [comment]
Done.
