### ISSUE TITLE
Investigate website logging to make sure it is appropriate and useful.

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#120]
There's a lot of logging. Perhaps some of the INFO logging could be at DEBUG?

**Comment by markpatton** [comment]
I see, there is a profile which sets the logging. I think I will change one to "production".

**Comment by markpatton** [comment]
The logging level set in the with the production profile still seems to allow a lot of logging

**Comment by jabrah** [comment]
Dropped in _logging.properties_ into websites, configurable with Maven filtering.
