### ISSUE TITLE
Build fails in Bamboo caused by rosa-search dependency: lucene-latin-stemmer

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#137]
Workaround that works locally is to do a `mvn install` of the _jhu-digital-manuscripts/lucene-latin-adapter_. Subsequent maven builds of _rosa2_ will then pick up the dependency from the local repo. 

If the artifact were made available somewhere, this would likely solve the build issue in Bamboo.

**Comment by markpatton** [comment]
Added a bamboo project for the lucene latin stemmer.
