### ISSUE TITLE
Search service needs special handling for transcribers marks

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#138]
There are brackets, contractions, abbreviations, ligatures, and deleted text. See the transcribers manual.

Jaap comments on brackets:
I would say it would probably be best to 'filter' the square brackets so that they don't affect search results (e.g. in order to find all instances of Caesar in the marginal notes, one does not have to write 'Ca[e]sar'). The disadvantage of this approach might be that we conflate all the uses of the square brackets, which are also used to denote uncertainty or missing letters (e.g. 'C[...]ar'). This, however, should not influence search results too much, I reckon. For our uses of the square brackets, see the Manual, pp. 66-71

**Comment by markpatton** [comment]
Check current behavior to find cases that show we actually need the special handling.

**Comment by jabrah** [comment]
Now merged into master (8255b72732504f985ef937020be8065448e55e46).

When transcriber marks are present in the context, the searched word is sometimes not highlighted properly. 

Example: Search for word 'supra'
Expecting words in context: **supra**, **s[upr]a**, **su[pra]**, etc
Actual context will sometimes highlight correctly, sometimes look like: s[upr]**a**

**Comment by markpatton** [comment]
There were a few lingering issues with the search context that caused us to instead strip the transcribers marks before indexing. The consequence is that the search result context display does not include the transcribers marks. But the implementation is much simpler.
