### ISSUE TITLE
Add ability of user to search by field language

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#141]
Have to have separate field for each language and then add support for grouping fields? Better way to do this? 

Add notion of inflecting search field with a qualifier? field.qualifier:'blah'? Instead more general notion of field group?

Also need more detailed search info response?

**Comment by jabrah** [comment]
Possible UI:
https://drive.google.com/open?id=1pgmiaImgZjp112z_I0hDdspFMAUqyLMfwu6COz9cTlg

Second options seems to be more popular

**Comment by markpatton** [comment]
Instead just add another "Language" field.
