### ISSUE TITLE
Figure out order of search fields in UI

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#149]
Consult with team.

**Comment by jabrah** [comment]
Per AOR Google Group discussion (https://groups.google.com/d/msg/archaeologyofreading/3KtqYKPhW3o/D6WIf8ctCQAJ), the preferred ordering has some fields listed as subcategories.

* Marginalia
  * Marginalia language
  * Book
  * People
  * Place
  * Cross_reference
  * Emphasis
* Symbol
* Underline 
* Mark
* Numeral
* Drawing
* Errata
* Language
* Method

However, if this is not feasible for whatever reason, order of field "importance" is also OK:

* Marginalia
* Symbol
* Underline 
* Mark
* Book
* People
* Place
* Language
* Marginalia language
* Numeral
* Drawing
* Errata
* Emphasis
* Cross_reference
* Method
