### ISSUE TITLE
Cleanup Aor stats tool

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#153]
Tool should run off the archive and needs a lot of cleanup.

**Comment by markpatton** [comment]
Make sure produces all needed spreadsheets such as book_totals.csv.

**Comment by jabrah** [comment]
Needs more comprehensive testing.

`AnnotationStatsWriterTest#testGetStatsFolgers1r` needs to be investigated. This test has inconsistent behavior, working in IDEA, but not on command line, sometimes working locally, but not on Bamboo....

**Comment by markpatton** [comment]
Probably no longer relevant.
