### ISSUE TITLE
Setup wordpress site

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#173]
http://cnidemo.sharedblogs.library.jhu.edu/

Graphic design should indicate content from AoR, Rose, and Pizan.
Link to custom integrated Mirador
Title: Humanities Data Library
Paragraph of explanation

**Comment by jabrah** [comment]
http://cnidemo.sharedblogs.library.jhu.edu/cnidemo/

Site now has the cni-demo viewer. We now need some text to show on the main page, plus a link to this viewer.
