### ISSUE TITLE
Select content for demo

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#174]
Choose 2-3 books from Rose, Pizan, and AoR that might show some interesting searches. 

Document content and search ideas. If some collection, like Pizan, has nothing of interest to search, look for related data or metadata that could be added.

**Comment by jabrah** [comment]
* AOR
  * L. Domenichi, Facetie (1571) & L. Guicciardini, Detti et Fatti (1571)
  * S. Frontinus, Strategemes of warre (1539)
  * T. Livius, Romanae historiae principis (1555)
* Rose
  * Walters Art Museum, W. 143
  * Morgan Library & Museum, M. 948
  * Bodleian Library, MS Selden Supra 57

Pizan?

**Comment by jabrah** [comment]
Now should decide on logos to display in Mirador
