### ISSUE TITLE
Add search support to manifest browser

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#176]
User should be able to search across all the collections and in a single collection.
User should be able to browse search results.

**Comment by jabrah** [comment]
[Commit 0c57c43](https://github.com/jhu-digital-manuscripts/mirador/commit/0c57c43436083c1b78d50cd977f5fceadedf87b6) in the JHU Mirador fork has support for for searching in the manifest browser. Search results are displayed and are clickable. A clicked result will modify the currently selected window to show the search result.

Some bugs exist and some features still need to be addressed:
* [ ] Clicking search result to navigate to the place it describes clears the search result, but the result pop-up in the manifest browser is still visible (in browser).
* [ ] There is no paging

**Comment by markpatton** [comment]
In the dropdown the collections could use nicer labels then "rosecollection" etc.

**Comment by jabrah** [comment]
(3b49ba95143b896612b9b64bd7e22189adc94f4c) adds a *label* field to the props file of each collection that is read by the IIIF endpoint.

**Comment by markpatton** [comment]
Should modify the styling so that the text in the search field boxes is not so faint.

**Comment by jabrah** [comment]
(494cb0f530f173ba246a8c3fcd5689a77074bc62) in our Mirador fork now addresses this. It also disables the basic search when the advanced search is active to hopefully clear up some UI confusion.
