### ISSUE TITLE
In manifest browser, indicate which collection a manifest is from

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#177]
Possibly use logo image.

**Comment by jabrah** [comment]
With a small change (https://github.com/jhu-digital-manuscripts/mirador/commit/b1b14ee75129e38e66603d005c2da6d1cd16670b), Mirador can now pick up the "location" property in the initial config, making it possible to properly assign logos to each collection loaded into Mirador.

Note that the AOR collection assigns thumbnails in each manifest that will override this setting. This should be modified to either point to a better image, or just removed.

**Comment by jabrah** [comment]
Should we remove the "thumbnail" property from the AOR IIIF manifests? Or just force Mirador to ignore the thumbnail?

**Comment by markpatton** [comment]
Rose and Pizan look good. Now just need an icon for AoR.
