### ISSUE TITLE
Choose search fields for all collection search and implement them

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#179]

**Comment by jabrah** [comment]
* **Title** : book/manuscript title, can include titles from Rose texts
* **Repo** : current repository
* **Description** : any less structured data describing the item
* **People** : any names of people, can include authors, references to other people in the text, fictional characters, etc
* **Places** : any names of places, can include current location of the item (should this be the case?) or locations mentioned in the text
