### ISSUE TITLE
Decide on facets for DLMM

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#192]
Proposed:

Rosa/Pizan will use the same browsing categories that are available in old websites:
  * Repository
  * Common name
  * Current location
  * Date
  * Origin
  * Type
  * Illustrations
  * Folios
  * Transcription

What should AOR use?
  * Author
  * Reader - might be more interesting in AOR2 with the addition more readers other than Harvey
  * Repository
  * Title (or Common Name)
  * Date

Perhaps we could pose the question to the AOR Google Group on what facets they would like to see.

**Comment by markpatton** [comment]
No need to think about AoR facets just yet.
