### ISSUE TITLE
Investigate the "Add external object" input to make it compatible with browsing.

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#206]
Input field in Mirador labeled: _Add new object from URL_

By the nature of the category browser, these external manifests will not be counted or included in any category. However, these objects _should_ be visible only under the condition that no categories are selected.

Until this behavior can be verified, this field should be hidden in the viewer.

**Comment by jabrah** [comment]
We can easily disable this input by modifying the Mirador initial config:

``` javascript
{
  ...
  "showAddFromURLBox": false
  ...
}
```

**Comment by markpatton** [comment]
I think it should be disabled.
