### ISSUE TITLE
Abstract out handling of image naming conventions

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#25]

**Comment by jabrah** [comment]
Will need to sit down and think about this, but a quick first cut in a separate branch: 

<https://github.com/jhu-digital-manuscripts/rosa2/blob/presentation-transformer-refactor/rosa-archive/rosa-archive-core/src/main/java/rosa/archive/core/ArchiveNameParser.java>

**Comment by jabrah** [comment]
First pass at abstraction done. [AbstractNameParser](https://github.com/jhu-digital-manuscripts/rosa2/blob/master/rosa-archive/rosa-archive-core/src/main/java/rosa/archive/core/ArchiveNameParser.java) from above merged into master and modified.
