### ISSUE TITLE
Import and validate the transcriptions

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#260]

**Comment by jabrah** [comment]
We should postpone this until we are ready to launch the updated AOR2 viewer.

The current AOR1 viewer still pulls data directly from the archive over NFS. Importing the updated data might break the data parsing of the AOR1 viewer, since all AOR1 data was updated to the AOR2 schema.

**Comment by markpatton** [comment]
Implications for AoR 1 migration.

**Comment by markpatton** [comment]
Done.
