### ISSUE TITLE
Add two missing images back to Dorn book

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#293]
There apparently were issues during digitization and we didn't get image for two pages in the Dorn book. It seems that we cannot go back and get images for these pages. Using these low quality images was given the OK by Jaap. Images for download at the link.

https://groups.google.com/forum/#!topic/archaeologyofreading/R5cZkLBoYMc

Page ordering: 
```
_27
IMG_7104
IMG_7068
_28
```

**Comment by markpatton** [comment]
Done.
