### ISSUE TITLE
Modify searchability of AOR2 annotations

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#308]
* [x]  **Hand** field should be changed to _reader_, as this was the original intent
* [x] **Calculation** should be tokenized during indexing, probably using _english_ analyzer
* [x] A search for `table:'fire'` yields oddly formatted results
![image](https://user-images.githubusercontent.com/5167587/36104579-66345ab8-0fe0-11e8-87e6-71eba0cc813d.png)
* [ ] Investigate **drawing**. Searching for `drawing:'face'` only yields 3 results, though more are expected

**Comment by jabrah** [comment]
One can easily find it when searching for a number that appears in the annotation. However, looking for the English words _"that is"_  will not work because of how calculations are indexed. Calculations use the `EnglishAnalyzer` in Lucene, which has the default behavior of ignoring some common words that tend to not carry much meaning. Both words _that_ and _is_ appear on this list of ignored words.

**Comment by markpatton** [comment]
Won't fix.
