### ISSUE TITLE
Unexpected search results when searching within book Ovid

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#310]
When searching for 'dee' in marginalia (advanced search) or 'John Dee' in people (advanced search) within the Ovid, the search doesn't return any results. This is strange, considering the fact that on the title page of the Ovid Dee's name appears (see the XML file: https://github.com/livesandletters/aor/blob/master/Ovid/009.xml)

**Comment by markpatton** [comment]
Works now.
