### ISSUE TITLE
File changes to RCP9986-1 are needed. We will also need to redeploy to propagate changes to viewers

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#423]
RCP9986 needs some updating.

The front matter pastedown is misnamed. We should also remove a `description.xml~` renmant.

- [x] Remove temp files from manual processing (they have trailing `~`)
- [x] Rename XML file
- [x] Rename image
- [x] Update filemap
- [x] Update images.csv file 
- [x] Update SHA1SUM file
- [ ] Redeploy IIIF backend for appropriate viewers (jdm, maybe rosetest)

**Comment by markpatton** [comment]
Test when deploy new aor endpoint.

**Comment by markpatton** [comment]
Looks like frontmatter pastdown is missing on image server. Check JP2.

**Comment by markpatton** [comment]
Renamed pastedown jp2 in image server. Now working.
