### ISSUE TITLE
Need different text when nothing in DLMM sidebar.

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#425]
The current text "No textual or symbolic marginalia on this page" does not make sense.

**Comment by cyork** [comment]
It should not have any text if there is nothing there.

**Comment by jabrah** [comment]
If we simply want no text to be displayed when there are no annotations to show, we can do a possibly gross thing. For DLMM, we can add a new CSS rule that targets only this message in the sidebar, which happens to have a CSS class that is not used anywhere else in the application. If this is added to the DLMM's `index.html` it should "just work" 

```
.messages .empty {
  display: none;
}
```
