### ISSUE TITLE
Location bar not updating

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#432]
If you visit https://www.archaeologyofreading.org/viewer/#aor/PrincetonPA6452/ it will take you to the home page. (This may be fine, have to look at the url patterns we agreed on.) Subsequently the location bar will not update as you navigate

**Comment by jabrah** [comment]
In order for a manifest URL to resolve, it needs a view (and possibly canvas name) appended, so `#aor/PrincetonPA6452/thumb` should be fine.

A real bug that comes from the above URL is that the viewer doesn't recover from the invalid URL

**Comment by jabrah** [comment]
https://github.com/jhu-digital-manuscripts/mirador/pull/93
