### ISSUE TITLE
USTC links on AoR are broken

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#434]
As reported by Matthew Symonds:

The Universal Short-Title Catalogue (USTC) has recently undergone an extensive redesign, in the process of which they have repatterned their URL permanlinks and thus managed to break all the links we have to their site. 

For instance, try to open the USTC link to “Fiue Hundred Pointes of Good Husbandrie” at the bottom of the annotation panel on this page:

https://archaeologyofreading.org/viewer/#aor/PrincetonRB16th99a/1v/image

You will be taken to a blank page on USTC:

https://ustc.ac.uk/index.php/record/505447

The intended permalink is now here:

https://ustc.ac.uk/editions/505447

Fortunately, the individual record number for each USTC entry has remained the same, so it seems that the problem is one of switching URL patterns from the current 

ustc.ac.uk/index.php/record/[recordnumber]

to the new pattern 

ustc.ac.uk/editions/[recordnumber]

**Comment by jabrah** [comment]
`books.csv` was updated and the IIIF endpoint rebuilt. Now showing correct links. Just waiting to deploy to prod now
