### ISSUE TITLE
Investigate rotation in mirador 2

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#52]
Determine if rotation support is in the roadmap.
If not, do some preliminary investigation to determine the difficulty of add it.

**Comment by markpatton** [comment]
See https://github.com/thehabes/m2 for a fork with rotation support.

**Comment by jabrah** [comment]
This feature is still in the works. Current implementation allows for rotation in 90 or 180 degree steps. Link below shows some screenshots of the proposed rotation widget. It includes +- 90 degree rotation, +180 degree rotation, as well as several other image manipulations.

This feature has not yet made it into the Mirador release. It should make it in for the Mirador 2.1 release, date TBA.

![Rotation widget hidden](http://i.imgur.com/f05RN0S.png)

![Rotation widget visible](http://i.imgur.com/5YRqjiK.png)

![Rotation widget, rotate image 90deg](http://i.imgur.com/qo9TYFx.png)
