### ISSUE TITLE
Poor handling of missing collection

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#54]
curl http://rosetest.library.jhu.edu/iiif-pres/collection/aor leads to a 500 and a stack trace with a java.nio.file.NoSuchFileException.

 The internal services should be returning null when asked for a resource that doesn't exist. Then the HTTP endpoint should probably be returning 404.

**Comment by jabrah** [comment]
Updated Fix: https://github.com/jhu-digital-manuscripts/rosa2/commit/5a7ecac1ba3cc096ffedfa280991e3eb891e716f
