### ISSUE TITLE
Fix transcriptions so they are valid TEI

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#56]
Have to fix some transcriptions in place.
The others are generated from text files and the generator will need to be fixed.
Also update tests to check validity.

**Comment by jabrah** [comment]
Should also update any book description files to be valid TEI where applicable.

`<book_id>.desecription_<lang_code>.xml`

**Comment by jabrah** [comment]
CoxMacro, Douce332, LudwigXV7, SeldonSupra57 have been updated. These had TEI generated from individual page transcriptions in .txt files.

Douce195, Morgan948, Walters143 must now be updated. They have TEI basically generated by hand.

**Comment by jabrah** [comment]
All description XML files are now valid TEI. Only Francais1563 english description and Frenoble608 french description were invalid.

**Comment by jabrah** [comment]
The rest of the TEI XML transcriptions have been fixed manually. These steps were taken:

* DELETE: all self closing lg tags `<lg type="couplet"/>
* DELETE: all divs surrounding figures, making sure any enclosed `<note>` tags are moved inside the figure.

```
<div type="miniature">
  <!-- Figure is here -->
</div>

```
* ADD type attribute to all figure tags: `<figure>  -->  <figure type="miniature">`
* ADD full TEI header to top of document:

```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.tei-c.org/ns/1.0    http://www.tei-c.org/release/xml/tei/custom/schema/xsd/tei_ms.xsd">
<teiHeader>
  <fileDesc>
    <titleStmt>
      <title></title>
    </titleStmt>
    <publicationStmt>
      <distributor>MSEL</distributor>
    </publicationStmt>
    <sourceDesc>
      <p></p>
    </sourceDesc>
  </fileDesc>
</teiHeader>

<text>
<body>
```

* ADD all applicable closing tags:

```
</div>  (this was deleted when removing all divs surrounding figure tags)
</body>
</text>
</TEI>
```
