### ISSUE TITLE
Design and implement AoR search backend

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#66]
See use cases. Attempt to make generic.

**Comment by jabrah** [comment]
MarpP finished the backend search code. Need to hook it up through GWT RPC.

**Comment by jabrah** [comment]
Search service indexes transcriptions, must make sure different data from transcriptions are indexed in correct search fields.

**Comment by markpatton** [comment]
See https://github.com/jhu-digital-manuscripts/rosa2/wiki/JHIIIF-Search for in progress documentation.
