### ISSUE TITLE
Make AoR data crawlable by google

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#74]

**Comment by jabrah** [comment]
A few links from Google:

The old way of crawling AJAX based websites has been deprecated:
https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html

New recommendations
https://webmasters.googleblog.com/2014/10/updating-our-technical-webmaster.html

**Comment by jabrah** [comment]
From a Google Webmaster account, one can simulate the Google crawler:
https://support.google.com/webmasters/answer/6066468?rd=2
