### ISSUE TITLE
Update statistics gathered by AoR tool

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#85]
* Update documentation on wiki
* Add spreadsheet with data for each commit
  * Timestamp
  * Commit message
  * Indicate schema changes somehow?
* Unit test
* New command that gathers stats over the entire repository history

**Comment by jabrah** [comment]
Should avoid requirement of having git installed on system. Investigating [JGit](http://www.eclipse.org/jgit/)

**Comment by jabrah** [comment]
Commit f3a17c0b42a7cea57cf4892a1a8b9f6b344bccd9: introduces function to aor stats tool, 'git-stats' that takes a single argument, the URL to a Github repo. This command will temporarily clone this repository and generate statistics for every commit in the repo. Two CSVs are generated while the tool runs, 'books.csv' and 'commits.csv' in the current directory

**Comment by jabrah** [comment]
- [ ] Add deleted, modified, and added stats to both spreadsheets.
- [ ] Add "parent commit" column to commits.csv
- [ ] Change word definition to char sequences separated by whitespace OR punctuation (stop counting punctuation).
- [ ] New spreadsheets: vocab counts, for each annotation type and language, example: marginalia_la.csv AND marginalia_en.csv, etc
- [ ] In <book_name>.csv (spreadsheet that aggregates per page) add a logical page number for each page (1 to N)

We also need a better understanding of Git history, generate a visual representation of the git commit graph.

**Comment by jabrah** [comment]
```
git log --graph --pretty=oneline --abbrev-commit --decorate --all
```

Command for git to generate a nice graph display for the commit history.
