### ISSUE TITLE
Add rotation support to Mirador 2

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/rosa2#89]
Should support 90 degree rotation. It's on the roadmap.

**Comment by jabrah** [comment]
http://rosetest.library.jhu.edu/mirador-rotation/

Semi-working demo. There is a bug with Openseadragon causing some weird behavior with rotated images, most pronounced with rotation +/- 90°. Bug is known, but it seems that no one is actively working on it.

https://github.com/openseadragon/openseadragon/issues/567

**Comment by jabrah** [comment]
Rotation implementation already recognized by Mirador devs (not merged): https://github.com/thehabes/mirador

**Comment by jabrah** [comment]
Closing: this issue is handled in our Mirador fork: 

https://github.com/jhu-digital-manuscripts/mirador/commits/jhu-rotation
