### ISSUE TITLE
Rose site first pass issues

### ISSUE THREAD

**Issue by jabrah** [jhu-digital-manuscripts/rosa2#92]
- [x] Search does not like spaces
- [x] Search token not properly updated in Advanced Search view
- [x] Missing favicon: GET http://rosetest.library.jhu.edu/favicon.ico  401 (Unauthorized) 
- [x] CSS loading from http://www.css-spinners.com/css/spinner/spinner.css ??
- [x] No longer "Home" in sidebar. But maybe good riddance? (Fine)
- [x] Clicking on left sidebar highlights in yellow, but can't see text
- [x] Rose summary text has full links to manuscripts instead of being relative. 
- [x] Clicking on extant manuscripts took a while and went to collection spreadsheet.
- [x] Collection spreadsheet slow to load and does not show correct data.
- [x] Narrative sections list. Cannot click on id to search.
- [x] From Collection spreadsheet clicking on ms names takes to description, but sidebar not highlighted correctly.
- [x] Select by very slow to load. Can we cache more on servlet startup?
- [x] Select browser has wrong cursor sometimes.
- ~~Select browser columns do not have titles.~~
- [x] Illustration titles view cannot click to search
- [x] When go to select browser, always have something selected.
- ~~I wonder if select browser should go and have first column be type....~~
- [x] Hung when selecting by date.
- Asked to log into rosetest when clicking on 1r to go to ms view. **FSI server config?**
- [x] Sidebar has no Book, turner, browser portion
- [x] Going back and forth between book view and browsing, got hangs loading stuff
- [x] SEVERE: Failed to load image list for book. [rosecollection:Arsenal2872]com.google.gwt.user.client.rpc.StatusCodeException: 500 Internal Server Error The call failed on the server; see server log for details
- ~~Unify various caches: archive data service, search service~~
- [x] Illustration titles display IDs, should fetch name from illustration_titles.csv before display
- [x] Illustration titles not indexed correctly?
- [x] Not all pages have headers.
- [x] Sidebar links to not respect locale properly.

**Comment by jabrah** [comment]
For 'home' link in sidebar, one can click the banner.

**Comment by jabrah** [comment]
Max cache size increased to accommodate all rose books.

(https://github.com/jhu-digital-manuscripts/rosa2/blob/master/rosa-website/rosa-website-core/src/main/java/rosa/website/core/server/StoreAccessLayerImpl.java)

**Comment by jabrah** [comment]
Investigate selecting correct sidebar item for page refresh. Might not work in all cases.

**Comment by markpatton** [comment]
- [ ] Update collection spreadsheet to have correct column titles
- [ ] Update search context to look prettier by translating search fields to human readable names. See original site.
- [ ] Investigate why illustrations list is different on new site. See for example illustrations without positions.
- [ ] Character names view should have names in first column not ids.
- [ ] Help link missing on sidebar
- [ ] Various image views do not have headers
- [ ] In both page turners typing in a number like 10 and hitting enter does not jump to page.
- [ ] Select view uses a lot of vertical space. Could the cells be closer to the size of the text entries?
- [ ] Select by transcriptions doesn't show partial, full, none like original site
- [ ] No option to see transcriptions for LudwigXV7
- [ ] Show illustration description for LudwigXV7 does not show anything

**Comment by jabrah** [comment]
Bad links in the Library of Congress manuscripts description

**Comment by jabrah** [comment]
- [ ] Links to read/view books that do not exist fail with no message to user.
- [ ] General failures do not give feedback to user.

**Comment by jabrah** [comment]
Still no manuscript reported as having "complete" transcriptions. Should list four: Douce195, SeldenSupra57, Morgan948, Walters143.

**Comment by jabrah** [comment]
"Position" column in illustration titles table may not be correct. Compare positions from original Roman de la Rose to current.

**Comment by jabrah** [comment]
Morgan 8r, no transcriptions...
